services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
 #   user: uid:gid
    security_opt:
      - systempaths=unconfined # Unmasks all system paths
      - apparmor=unconfined
      

    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    #Mounts:
    #  - /media/pc/usb:/test:rw,rshared    
    devices:
      - /dev/mali0:/dev/mali0
      - /dev/dri:/dev/dri
      - /dev/mpp_service:/dev/mpp_service
      - /dev/dma_heap:/dev/dma_heap
      - /dev/rga:/dev/rga
      

  
    volumes:
      - /path/to/config:/config
      - /path/to/cache:/cache
      - /path/to/media:/new
      - /home/pc/Myusb:/media:rw,shared
      - /home/pc/sftp_remote:/mediaremote:rw,shared      
      - /lib/firmware:/lib/firmware
      
      #/lib/firmware/mali_csffw_g15p0/mali_csffw.bin
#/lib/firmware/mali_csffw_g18p0/mali_csffw.bin
#/lib/firmware/mali_csffw_g17p0/mali_csffw.bin

      #- /usr/lib/aarch64-linux-gnu/libmali-x11/libmali-valhall-g610-g13p0-x11-wayland-gbm.so:/usr/lib/libmali.so
      #- /etc/OpenCL/vendors:/etc/OpenCL/vendors:ro
      # - /media/pc/usb:/test:rw,shared

      # Optional - extra fonts to be used during transcoding with subtitle burn-in
      - type: bind
        source: /path/to/fonts
        target: /usr/local/share/fonts/custom
        read_only: true
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - JELLYFIN_PublishedServerUrl=192.168.1.9
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'

    networks:
      - net_default

networks:
  net_default:
    external: true
    
